// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1681249797);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1681249826);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1681249506);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1681249790);
user_pref("browser.search.region", "US");
user_pref("browser.startup.homepage_override.buildID", "20230411042149");
user_pref("browser.startup.homepage_override.mstone", "112.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"save-to-pocket-button\"],\"dirtyAreaCache\":[],\"currentVersion\":19,\"newElementCount\":0}");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "112.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230411042149");
user_pref("extensions.lastAppVersion", "112.0");
user_pref("extensions.lastPlatformVersion", "112.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3666ed61-1148-4b89-986c-f098b67b4817\",\"pictureinpicture@mozilla.org\":\"d418cc9c-f2c2-4737-b1cc-5dd8c7e7aacd\",\"screenshots@mozilla.org\":\"6e69772b-4cb4-43ef-92ac-412f8148370f\",\"default-theme@mozilla.org\":\"5fc5c998-a95a-4a20-bf8e-fffcfbdf4112\",\"google@search.mozilla.org\":\"f31c0592-a2ec-486b-83e9-bfa035092b3f\",\"amazondotcom@search.mozilla.org\":\"52a30224-cd37-4df1-ba22-a1febf487b5f\",\"wikipedia@search.mozilla.org\":\"ecb81980-048e-461a-a37d-7f9b14909cfd\",\"bing@search.mozilla.org\":\"dc372c1b-1de4-43ad-be17-961850fb5fd5\",\"ddg@search.mozilla.org\":\"b7fd051e-9fd8-4fe0-b86a-a80c5eb8d9bc\",\"ebay@search.mozilla.org\":\"ca59c6fc-05d4-40ff-a16b-3773f1d4d335\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("security.sandbox.content.tempDirSuffix", "b88b54dc-0db0-40c6-bb11-3a10ffdb3c0e");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1681228635042\"");
user_pref("services.settings.last_update_seconds", 1681249797);
user_pref("services.settings.main.addons-manager-settings.last_check", 1681249797);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1681249797);
user_pref("services.settings.main.cookie-banner-rules-list.last_check", 1681249797);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1681249797);
user_pref("services.settings.main.devtools-devices.last_check", 1681249797);
user_pref("services.settings.main.doh-config.last_check", 1681249797);
user_pref("services.settings.main.doh-providers.last_check", 1681249797);
user_pref("services.settings.main.hijack-blocklists.last_check", 1681249797);
user_pref("services.settings.main.language-dictionaries.last_check", 1681249797);
user_pref("services.settings.main.password-recipes.last_check", 1681249797);
user_pref("services.settings.main.password-rules.last_check", 1681249797);
user_pref("services.settings.main.search-config.last_check", 1681249797);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1681249797);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1681249797);
user_pref("services.settings.main.sites-classification.last_check", 1681249797);
user_pref("services.settings.main.top-sites.last_check", 1681249797);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1681249797);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1681249797);
user_pref("toolkit.startup.last_success", 1681249759);
user_pref("toolkit.startup.recent_crashes", 4);
user_pref("toolkit.telemetry.cachedClientID", "bbe85f75-981e-466f-a567-1d3665f82e47");
user_pref("toolkit.telemetry.previousBuildID", "20230411042149");
